version: '3'
services:
  go-web-app:
    restart: always 
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=aaravsibbal.com
      - LETSENCRYPT_HOST=aaravsibbal.com